### ISSUE TITLE
Error : don't know how to set callback function

### ISSUE THREAD

**Issue by jkarthic** [lwahonen/node-ffi-napi#7]
When I try to pass a callback function as an argument, I get the following error.

```
    at Function.set (/Users/karthick/work/node_modules/.pnpm/@lwahonen+ffi-napi@4.0.12/node_modules/@lwahonen/ffi-napi/lib/function.js:107:11)
    at Object.set (/Users/karthick/work/node_modules/.pnpm/@lwahonen+ref-napi@4.0.8/node_modules/@lwahonen/ref-napi/lib/ref.js:492:10)
    at Object.alloc (/Users/karthick/work/node_modules/.pnpm/@lwahonen+ref-napi@4.0.8/node_modules/@lwahonen/ref-napi/lib/ref.js:526:13)
    at Object.proxy [as asr_start] (/Users/karthick/work/node_modules/.pnpm/@lwahonen+ffi-napi@4.0.12/node_modules/@lwahonen/ffi-napi/lib/_foreign_function.js:50:28)
```

I found that this error stems from the fact that `function.js` expects a `value` of type `Buffer` or `function`, whereas the type of value passed is `PointerBuffer`.

**Comment by fanybook** [comment]
me too

because ffi.Callback not a Buffer

**Comment by fanybook** [comment]
@lwahonen i has hacked it, it can works

Can you update the npm package

**Comment by lwahonen** [comment]
I do not know what you mean by you being hacked. This is not updated anymore
